#!/bin/sh

#-------------------------------------------------------------
# GNU INDENT configuration
#-------------------------------------------------------------

function gnu_indent()
{
version=`gnuindent --version 2>/dev/null`
if test "x$version" = "x"; then
  version=`indent --version 2>/dev/null`
  if test "x$version" = "x"; then
    echo "GStreamer git pre-commit hook:"
    echo "Did not find GNU indent, please install it before continuing."
    return 1
  fi
  INDENT=indent
else
  INDENT=gnuindent
fi

case `$INDENT --version` in
  GNU*)
      ;;
  default)
      echo "Did not find GNU indent, please install it before continuing."
      echo "(Found $INDENT, but it doesn't seem to be GNU indent)"
      return 1
      ;;
esac

$INDENT \
  --braces-on-if-line \
  --case-brace-indentation0 \
  --case-indentation2 \
  --braces-after-struct-decl-line \
  --line-length80 \
  --no-tabs \
  --cuddle-else \
  --dont-line-up-parentheses \
  --continuation-indentation4 \
  --honour-newlines \
  --tab-size8 \
  --indent-level2 \
  --leave-preprocessor-space \
  $1
  return $?
}

#-------------------------------------------------------------
# uncrustify configuration
#-------------------------------------------------------------

function uncrustify_indent()
{
 if ! [ -x "$(command -v uncrustify)" ]; then
  echo 'Error: uncrustify is not installed.' >&2
  echo 'Needed for OCL language.' >&2
  return 1
fi
uncrustify --replace -q -c $1/uncrustify.config $2
return $?
}


#-------------------------------------------------------------
# Iterate script parameters and call an indent utility
# depending of file's extension
#-------------------------------------------------------------

BASEDIR=$(dirname "$0")

for arg in "$@"
    do case "$arg" in
    *.m )
    #OCL language
    uncrustify_indent $BASEDIR $arg
    ;;
    *)
    #Any other   
    gnu_indent $arg
    ;;
    esac
    if [[ $? != 0 ]]; then exit $?; fi
done